import { Item } from './type/Item';

export const items: Item[] = [
  {
    id: 1,
    name: 'KATE',
    image: 'assets/img/1.jpeg',
    size: 'small',
    color: 'black',
    season: 'winter',
    stock: 3,
    price: 1390,
    newArrival: false,
  },
  {
    id: 2,
    name: 'LE 57',
    image: 'assets/img/2.jpeg',
    size: 'medium',
    color: 'white',
    season: 'summer',
    stock: 5,
    price: 2100,
    newArrival: true,
  },
  {
    id: 3,
    name: 'ICARE',
    image: 'assets/img/3.jpeg',
    size: 'large',
    color: 'black',
    season: 'winter',
    stock: 1,
    price: 3500,
    newArrival: true,
  },
  {
    id: 4,
    name: 'LE 5 À 7',
    image: 'assets/img/4.jpeg',
    size: 'medium',
    color: 'pink',
    season: 'summer',
    stock: 5,
    price: 1790,
    newArrival: true,
  },
  {
    id: 5,
    name: 'LE 5 À 7',
    image: 'assets/img/5.jpeg',
    size: 'medium',
    color: 'white',
    season: 'summer',
    stock: 2,
    price: 1790,
    newArrival: true,
  },
  {
    id: 6,
    name: 'GABY',
    image: 'assets/img/6.jpeg',
    size: 'medium',
    color: 'white',
    season: 'summer',
    stock: 3,
    price: 2100,
    newArrival: true,
  },
  {
    id: 7,
    name: 'CLASSIC',
    image: 'assets/img/7.jpeg',
    size: 'medium',
    color: 'pink',
    season: 'summer',
    stock: 3,
    price: 1750,
    newArrival: true,
  },
  {
    id: 8,
    name: 'GABY',
    image: 'assets/img/8.jpeg',
    size: 'mini',
    color: 'white',
    season: 'summer',
    stock: 7,
    price: 1750,
    newArrival: true,
  },
  {
    id: 9,
    name: 'PANIER',
    image: 'assets/img/9.jpeg',
    size: 'large',
    color: 'black',
    season: 'summer',
    stock: 7,
    price: 1250,
    newArrival: true,
  },
  {
    id: 10,
    name: 'ASTRO',
    image: 'assets/img/10.jpeg',
    size: 'large',
    color: 'black',
    season: 'winter',
    stock: 10,
    price: 1950,
    newArrival: false,
  },
  {
    id: 11,
    name: 'RIVE',
    image: 'assets/img/11.jpeg',
    size: 'large',
    color: 'black',
    season: 'summer',
    stock: 1,
    price: 1250,
    newArrival: false,
  },
  {
    id: 12,
    name: 'RIVE GAUCHE',
    image: 'assets/img/12.jpeg',
    size: 'medium',
    color: 'white',
    season: 'summer',
    stock: 1,
    price: 1150,
    newArrival: false,
  },
  {
    id: 13,
    name: 'KATE',
    image: 'assets/img/13.jpeg',
    size: 'medium',
    color: 'pink',
    season: 'summer',
    stock: 1,
    price: 1650,
    newArrival: true,
  },
  {
    id: 14,
    name: 'SADE',
    image: 'assets/img/14.jpeg',
    size: 'small',
    color: 'pink',
    season: 'summer',
    stock: 8,
    price: 1190,
    newArrival: false,
  },
  {
    id: 15,
    name: 'LE CARRE',
    image: 'assets/img/15.jpeg',
    size: 'medium',
    color: 'pink',
    season: 'summer',
    stock: 1,
    price: 2400,
    newArrival: true,
  },
  {
    id: 16,
    name: 'ENVELOPE',
    image: 'assets/img/16.jpeg',
    size: 'small',
    color: 'white',
    season: 'summer',
    stock: 2,
    price: 1950,
    newArrival: true,
  },
  {
    id: 17,
    name: 'UPTOWN ',
    image: 'assets/img/17.jpeg',
    size: 'small',
    color: 'white',
    season: 'summer',
    stock: 2,
    price: 450,
    newArrival: true,
  },
  {
    id: 18,
    name: 'UPTOWN',
    image: 'assets/img/18.jpeg',
    size: 'small',
    color: 'black',
    season: 'summer',
    stock: 6,
    price: 450,
    newArrival: true,
  },
  {
    id: 19,
    name: 'BAHIA',
    image: 'assets/img/19.jpeg',
    size: 'small',
    color: 'black',
    season: 'summer',
    stock: 6,
    price: 1390,
    newArrival: true,
  },
  {
    id: 20,
    name: 'LOU',
    image: 'assets/img/20.jpeg',
    size: 'small',
    color: 'pink',
    season: 'summer',
    stock: 6,
    price: 1190,
    newArrival: true,
  }
];